name: example
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  hetu_script_generator:
    path: ../
  hetu_script:
    git:
      url: https://github.com/hetu-script/hetu-script.git
      path: packages/hetu_script

dev_dependencies:
  hetu_script_generator:
    path: ../
  build_runner: ^2.4.0
  lints: ^6.0.0
  test: ^1.25.6
