name: hetu_script_generator
description: Generator for Hetu <-> Flutter bindings (annotations + build_runner generator).
version: 0.1.0
homepage: https://example.invalid/hetu_script_generator
repository: https://example.invalid/hetu_script_generator
environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  analyzer: ^5.10.0
  source_gen: ^1.3.2
  build: ^2.4.0
  code_builder: ^4.2.0
  dart_style: ^2.2.3
  hetu_script:
    git:
      url: https://github.com/hetu-script/hetu-script.git
      path: packages/hetu_script

dev_dependencies:
  build_runner: ^2.4.0
  build_test: ^2.0.0
  test: ^1.21.0

flutter:
  plugin:
    platforms: {}
